# Requête N°1.1
# On souhaite afficher tous les budgets de recherche et de transfert de technologie
# des collectivités territoriales de la région les Hauts de France


PREFIX dbo:<http://dbpedia.org/ontology/>
PREFIX dbp:<http://dbpedia.org/property/>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX ex:<http://test.org/>

Select ?Annee ?title ?suppTitle ?organization ?objectif ?valeur
Where {
	?p dbo:region "Hauts-de-France".
	?p dbo:Organization ?organization.
	?p dbo:year ?Annee.
	?p dbp:title ?title.
	?p dbo:abstract ?objectif.
	?p dbp:amount ?valeur.
 	OPTIONAL { ?p rdfs:comment ?suppTitle }
}
ORDER BY ?Annee



# Requête N°1.2
# On associe à la région Hauts de France son ancien nom, à savoir Nord pas de Calais


PREFIX dbo:<http://dbpedia.org/ontology/>
PREFIX dbp:<http://dbpedia.org/property/>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX ex:<http://test.org/>

INSERT {
	?p dbo:sameAs "NordPasdeCalais"
}
where {
	?p dbo:region "Hauts-de-France"
};
INSERT {
	?p dbo:sameAs "Hauts-de-France"
}
where {
	?p dbo:region "NordPasdeCalais"
};



# Requête N°1.3
# On test notre update en reprennant la requête N°1


PREFIX dbo:<http://dbpedia.org/ontology/>
PREFIX dbp:<http://dbpedia.org/property/>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX ex:<http://test.org/>

Select ?Annee ?region ?title ?suppTitle ?organization ?objectif ?valeur
Where {
	?p dbo:region "Hauts-de-France". 
  	?p dbo:sameAs ?region.
	?p dbo:Organization ?organization.
	?p dbo:year ?Annee.
	?p dbp:title ?title.
	?p dbo:abstract ?objectif.
	?p dbp:amount ?valeur.
 	OPTIONAL { ?p rdfs:comment ?suppTitle }
}
ORDER BY ?Annee


