# Requête N°1
# On souhaite afficher tous les budgets de recherche et de transfert de technologie
# des collectivités territoriales de la région les Hauts de France


PREFIX dbo:<http://dbpedia.org/ontology/>
PREFIX dbp:<http://dbpedia.org/property/>
PREFIX ex:<http://test.org/>
PREFIX frapo:<http://purl.org/cerif/frapo/>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>


SELECT ?annee ?indicateur ?indicateurEffort ?organization ?objectif ?valeur
WHERE {
	?p dbo:region "Hauts-de-France".
	?p dbo:Organization ?organization.
	?p dbo:year ?annee.
	?p frapo:BudgetInformation ?indicateur.
	?p frapo:appliesFor ?objectif.
	?p frapo:BudgetedAmount ?valeur.
 	OPTIONAL { ?p frapo:BudgetInformation ?indicateurEffort }
}
ORDER BY ?annee




# Requête N°2
# Classements des régions possédant le plus gros budget total de recherche et de transfert de technologie par année


PREFIX dbo:<http://dbpedia.org/ontology/>
PREFIX dbp:<http://dbpedia.org/property/>
PREFIX ex:<http://test.org/>
PREFIX frapo:<http://purl.org/cerif/frapo/>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>


SELECT ?annee ?region (sum(?valeur) as ?sommeValeur) 
WHERE {
  	?p dbo:year ?annee.
  	?p dbo:region ?region.
  	?p frapo:BudgetedAmount ?valeur.
  	?p dbo:percentage "0"^^xsd:boolean.
}
GROUP BY ?annee ?region
ORDER BY DESC(?annee) DESC(?sommeValeur)




# Requête N°3
# Financement de la recherche par région de entre 2007 et 2015

PREFIX dbo:<http://dbpedia.org/ontology/>
PREFIX dbp:<http://dbpedia.org/property/>
PREFIX ex:<http://test.org/>
PREFIX frapo:<http://purl.org/cerif/frapo/>
PREFIX owl:<http://www.w3.org/2002/07/owl#>
PREFIX rdf:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX db: <http://dbpedia.org/>

SELECT ?region ?objectif (sum(?montant) AS ?somme)
WHERE {
	?uri frapo:appliesFor ?objectif;
 		dbo:region ?region;
		frapo:BudgetedAmount ?montant.
  		dbo:percentage "0"^^xsd:boolean.
  	FILTER(?objectif IN ("Equipement de laboratoires", "Aides aux chercheurs", "Projets de la recherche publique"))
}
GROUP BY ?region ?indicateur
ORDER BY ?region




# Requête N°4
# Investissement par type de collectivité territoriale


PREFIX dbo:<http://dbpedia.org/ontology/>
PREFIX dbp:<http://dbpedia.org/property/>
PREFIX ex:<http://test.org/>
PREFIX frapo:<http://purl.org/cerif/frapo/>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>

SELECT ?coll (sum(?montant) AS ?somme) (GROUP_CONCAT(DISTINCT ?objectif; SEPARATOR=", ") AS ?objectifs)
WHERE {
 	?uri dbo:Organization ?coll;
 		frapo:appliesFor ?objectif;
		frapo:BudgetedAmount ?montant.
      		dbo:percentage "0"^^xsd:boolean.
}
GROUP BY ?coll
ORDER BY DESC(?somme)
