PREFIX dbo:<http://dbpedia.org/ontology/>
PREFIX frapo:<http://purl.org/cerif/frapo/>
PREFIX owl:<http://www.w3.org/2002/07/owl#>
PREFIX schema: <http://schema.org/>
PREFIX igeo: <http://rdf.insee.fr/def/geo#>

SELECT DISTINCT ?codeRegion ?region ?codeRegionOther ?regionOther
WHERE {
  ?x a frapo:Funding;
     dbo:code ?codeRegion;
     dbo:region ?region.
  ?codeRegion owl:sameAs ?codeRegionOther.
  Graph <http://localhost:3030/clem> {
	?y a schema:dataset;
    	igeo:codeRegion ?codeRegionOther;
		igeo:nom ?regionOther.    
  }
}