PREFIX dbp: <http://dbpedia.org/property/>
PREFIX ex: <http://ex.org/a#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX frapo: <http://purl.org/cerif/frapo/>

CONSTRUCT {
	?URI a frapo:Funding;

		dbo:Place [frapo:hasLocation ?Zone_géographique;
					frapo:hasCode ?code_zone_geo];

		frapo:hasDeliveryDate ?Année;
		
		ex:indicateur [frapo:hasCode ?code_indicateur;
						ex:typIndic ?Indicateur];

		ex:personnel [frapo:hasCode ?code_type_pers;
						ex:typePersonnel ?Type_de_personnel];

		ex:intensite [frapo:hasCode ?code_intensite;
						ex:typeIntensite ?Intensité_technologique];

		ex:Secret ?Secret;

		ex:nonDisponible ?Non_disponible;

		ex:etatDonnee ?État_des_données;

		frapo:BudgetedAmount ?Valeur;
}
FROM <file:project.csv>
WHERE {
	BIND(URI(CONCAT('http://ex.org/donation/', ?code_zone_geo, ?Année, ?code_indicateur, ?code_type_pers, ?code_intensite)) AS ?URI)
	BIND (xsd:string(?Indicateur) AS ?Indicateur)
	BIND (xsd:string(?Type_de_personnel) AS ?Type_de_personnel)
	BIND (xsd:string(?Intensité_technologique) AS ?Intensité_technologique)
	BIND (xsd:boolean(?Secret) AS ?Secret)
	BIND (xsd:boolean(?Non_disponible) AS ?Non_disponible)
	BIND (xsd:boolean(?État_des_données) AS ?État_des_données)
}