PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX frapo: <http://purl.org/cerif/frapo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>


SELECT DISTINCT ?codeRegion ?region ?codeRegionOther ?regionOther
WHERE {
  ?x a frapo:Funding;
     dbo:code ?codeRegion.
  ?x dbo:region ?region.
  ?codeRegion owl:sameAs ?codeRegionOther.
  Service <http://localhost:3030/yvan> {
  	?z a frapo:Funding;
      dbo:Place ?t.
    ?t frapo:hasCode ?codeRegionOther.
  }
}